/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";


export default function Cessna(props) {
  const { nodes, materials } = useGLTF("./Cessna_172.gltf");
  const { viewport } = useThree()

  const ref = useRef()
  useFrame(({ mouse }) => {
    const x = (mouse.x * viewport.width) / 2
    const y = (mouse.y * viewport.height) / 2
    ref.current.position.set(x * 40, y * 40, 0)
    
  })

  return (
    <group {...props} dispose={null} scale={0.025}>
      <mesh
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
      />
    </group>
  );
}

useGLTF.preload("/Cessna_172.gltf");

