/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Hyungjung Kim (https://sketchfab.com/hyungjungkim)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/low-poly-cloud-81910476b24d4fc5a73c908d6c2a38a2
title: Low Poly Cloud
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Cloud(props) {
  const { nodes, materials } = useGLTF("/cloud.glb");
  return (
    <group {...props} dispose={null} scale={0.1}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials["Scene_-_Root"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cloud.glb");
