/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Plane(props) {
  const { nodes, materials } = useGLTF("./cube.glb");
  return (
    <group {...props} dispose={null} scale={0.25}>
      <mesh
        castShadow
        receiveShadow
        
        geometry={nodes.geometry_0_0.geometry}
        material={nodes.geometry_0_0.material}
      />
    </group>
  );
}

useGLTF.preload("/cube.glb");
