/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Skateboard(props) {
  const { nodes, materials } = useGLTF("/Skateboard.gltf");
  return (
    <group {...props} dispose={null} scale={0.1}>
      <group
        position={[0.58, -34.75, -13.74]}
        rotation={[1.06, -0.3, -0.16]}
        scale={0.5}
      >
        <group
          position={[-1.32, 16.65, -0.11]}
          rotation={[-0.25, 0, 0]}
          scale={0.32}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pasted__pasted__pCylinder17.geometry}
            material={materials.pasted__UnderBettery}
            position={[9.75, 22.7, -0.61]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[1, 2.04, 1]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pPipe1.geometry}
          material={materials.pasted__pasted__Metal_Tire}
          position={[0.11, 23.17, -3.38]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.62}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pPipe5.geometry}
          material={materials.pasted__pasted__Metal_Tire}
          position={[3.58, 23.17, -3.38]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.62}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pPipe6.geometry}
          material={materials.pasted__pasted__Metal_Tire}
          position={[3.58, 23.17, 3.9]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.62}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pPipe7.geometry}
          material={materials.pasted__pasted__Metal_Tire}
          position={[0.11, 23.17, 3.9]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.62}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pasted__pCylinder1.geometry}
          material={materials.pasted__Metal_Tire}
          position={[-0.17, 23.18, -3.4]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.52, 0.12, 0.52]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pasted__pCylinder2.geometry}
          material={materials.pasted__Metal_Tire}
          position={[3.3, 23.18, -3.4]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.52, 0.12, 0.52]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pasted__pCylinder3.geometry}
          material={materials.pasted__Metal_Tire}
          position={[3.3, 23.18, 3.88]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.52, 0.12, 0.52]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pasted__pCylinder4.geometry}
          material={materials.pasted__Metal_Tire}
          position={[-0.17, 23.18, 3.88]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.52, 0.12, 0.52]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pPipe10.geometry}
          material={materials.pasted__UnderBettery}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder20.geometry}
          material={materials.pasted__Tire}
          position={[0, 0, 7.28]}
          scale={1.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder19.geometry}
          material={materials.pasted__Tire}
          position={[3.47, 0, 7.28]}
          scale={1.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder16.geometry}
          material={materials.pasted__Tire}
          scale={1.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCube8.geometry}
          material={materials.pasted__UnderBettery}
          position={[2.73, 23.36, -2.78]}
          rotation={[-0.38, 0, Math.PI]}
          scale={[0.19, 0.23, 0.87]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder11.geometry}
          material={materials.pasted__UnderBettery}
          position={[2.64, 23.1, -3.47]}
          rotation={[-0.38, 0, Math.PI / 2]}
          scale={[0.39, 0.06, 0.39]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder13.geometry}
          material={materials.pasted__UnderBettery}
          position={[2.58, 23.19, -3.73]}
          rotation={[-0.38, 0, Math.PI / 2]}
          scale={[0.05, 0.01, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder12.geometry}
          material={materials.pasted__UnderBettery}
          position={[2.58, 22.82, -3.6]}
          rotation={[-0.38, 0, Math.PI / 2]}
          scale={[0.05, 0.01, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder14.geometry}
          material={materials.pasted__UnderBettery}
          position={[2.58, 23.4, -3.41]}
          rotation={[-0.38, 0, Math.PI / 2]}
          scale={[0.05, 0.01, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder15.geometry}
          material={materials.pasted__UnderBettery}
          position={[2.58, 22.97, -3.24]}
          rotation={[-0.38, 0, Math.PI / 2]}
          scale={[0.05, 0.01, 0.05]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder10.geometry}
          material={materials.lambert1}
          position={[2.68, 23.1, -3.47]}
          rotation={[-0.38, 0, Math.PI / 2]}
          scale={[0.45, 0.07, 0.45]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder9.geometry}
          material={materials.pasted__UnderBettery}
          position={[2.86, 23.11, -3.4]}
          rotation={[-0.38, 0, Math.PI / 2]}
          scale={[0.72, 0.66, 0.72]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCube7.geometry}
          material={materials.pasted__Engin}
          position={[1.71, 23.63, 0.61]}
          rotation={[0, 0, Math.PI]}
          scale={[1.89, 1.89, 1.92]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCube6.geometry}
          material={materials.pasted__Metal_Truck}
          position={[1.73, 24.09, -3.1]}
          rotation={[0, 0, Math.PI]}
          scale={[1.45, 0.09, 1.46]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCube5.geometry}
          material={materials.pasted__Metal_Truck}
          position={[3.15, 27.96, -2]}
          rotation={[Math.PI, 0, 0]}
          scale={[0.81, 0.94, 0.81]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCube10.geometry}
          material={materials.pasted__Metal_Truck}
          position={[1.72, 24.09, 3.55]}
          rotation={[Math.PI, 0, 0]}
          scale={[1.45, 0.09, 1.46]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCube9.geometry}
          material={materials.pasted__Metal_Truck}
          position={[0.3, 27.96, 2.46]}
          rotation={[0, 0, Math.PI]}
          scale={[0.81, 0.94, 0.81]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder18.geometry}
          material={materials.pasted__Tire}
          position={[3.47, 0, 0]}
          scale={1.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pasted__pasted__pCylinder1.geometry}
          material={materials.pasted__Board}
          position={[1.74, 22.7, 5]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={1.73}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Skateboard.gltf");

